### ISSUE TITLE
Type Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by tacocat777** [darcyclarke/Repo.js#45]
Trying to implement this awesome script on my github pages found here: https://tacocat777.github.io

I followed instructions from this article (https://www.codediesel.com/javascript/easily-embed-a-github-repo-onto-your-site/), but can't seem to get it to work.

It gets stuck loading and the console has this error output:
![akjsdf](https://user-images.githubusercontent.com/32477481/69044405-b7714c00-09a9-11ea-9f39-2b53b2ac3d1e.PNG)

**Comment by tacocat777** [comment]
Anyway I could see an example/implementation of this please?

**Comment by Oct4Pie** [comment]
Since the default branch is no longer `master`, you should add `branch: "main"`

```
<script>
    $(function() {
        $('#id').repo({
            user: 'user',
            name: 'repo-name',
            branch: 'main',
        });
    });
</script>
```
